# Generated by Django 4.2.1 on 2023-05-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0004_recipe_image_file_recipe_uploaded_at_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=200),
        ),
    ]
